### ISSUE TITLE
ImportError: DLL load failed while importing inplace_abn:

### ISSUE THREAD

**Issue by toyxyz** [pzc163/Comfyui-CatVTON#1]
Thanks for the nice work! 

I installed the node, put Detectron2 and DensePose in the site-packages, but got the following error 

C:\Comfy\ComfyUI_windows_portable_2\python_embeded\Lib\site-packages\torch\utils\cpp_extension.py:1967: UserWarning: TORCH_CUDA_ARCH_LIST is not set, all archs for visible cards are included for compilation.
If this is not desired, please set os.environ['TORCH_CUDA_ARCH_LIST'].
  warnings.warn(
Traceback (most recent call last):
  File "C:\Comfy\ComfyUI_windows_portable_2\ComfyUI\nodes.py", line 1931, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Comfy\ComfyUI_windows_portable_2\ComfyUI\custom_nodes\Comfyui-CatVTON\__init__.py", line 3, in <module>
    from .model.cloth_masker import AutoMasker as AM
  File "C:\Comfy\ComfyUI_windows_portable_2\ComfyUI\custom_nodes\Comfyui-CatVTON\model\cloth_masker.py", line 9, in <module>
    from ..model.SCHP import SCHP  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Comfy\ComfyUI_windows_portable_2\ComfyUI\custom_nodes\Comfyui-CatVTON\model\SCHP\__init__.py", line 1, in <module>
    from . import networks
  File "C:\Comfy\ComfyUI_windows_portable_2\ComfyUI\custom_nodes\Comfyui-CatVTON\model\SCHP\networks\__init__.py", line 3, in <module>
    from .AugmentCE2P import resnet101
  File "C:\Comfy\ComfyUI_windows_portable_2\ComfyUI\custom_nodes\Comfyui-CatVTON\model\SCHP\networks\AugmentCE2P.py", line 21, in <module>
    from ..modules import InPlaceABNSync
  File "C:\Comfy\ComfyUI_windows_portable_2\ComfyUI\custom_nodes\Comfyui-CatVTON\model\SCHP\modules\__init__.py", line 1, in <module>
    from .bn import ABN, InPlaceABN, InPlaceABNSync
  File "C:\Comfy\ComfyUI_windows_portable_2\ComfyUI\custom_nodes\Comfyui-CatVTON\model\SCHP\modules\bn.py", line 10, in <module>
    from .functions import *
  File "C:\Comfy\ComfyUI_windows_portable_2\ComfyUI\custom_nodes\Comfyui-CatVTON\model\SCHP\modules\functions.py", line 10, in <module>
    _backend = load(name="inplace_abn",
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Comfy\ComfyUI_windows_portable_2\python_embeded\Lib\site-packages\torch\utils\cpp_extension.py", line 1309, in load
    return _jit_compile(
           ^^^^^^^^^^^^^
  File "C:\Comfy\ComfyUI_windows_portable_2\python_embeded\Lib\site-packages\torch\utils\cpp_extension.py", line 1745, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Comfy\ComfyUI_windows_portable_2\python_embeded\Lib\site-packages\torch\utils\cpp_extension.py", line 2143, in _import_module_from_library
    module = importlib.util.module_from_spec(spec)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: DLL load failed while importing inplace_abn:The specified module could not be found

**Comment by pzc163** [comment]
First，type pip install to check  if detectron2 and detectron2-densepose==0.6 has been installed successfully under your Comfyui python environment. as below pic shown
![image](https://github.com/user-attachments/assets/da81761b-75eb-43cf-aa69-c1678c008557)
If not ,pls manually install detectron2 and densepose with below cli:
pip install git+https://github.com/facebookresearch/detectron2.git@v0.6
pip install git+https://github.com/facebookresearch/detectron2.git@v0.6#subdirectory=projects/DensePose
notice that before install detectron2 and densepose you need to install VS2019 and add VS2019 to your system environment variables path

**Comment by toyxyz** [comment]
Thanks! I installed dectron2 and densepose manually, but this time I got a new error. 

![image](https://github.com/user-attachments/assets/8fe23f79-8884-43de-b2a7-cce07e51ad7b)


C:\Comfy\ComfyUI_windows_portable_2\python_embeded\Lib\site-packages\torch\utils\cpp_extension.py:1967: UserWarning: TORCH_CUDA_ARCH_LIST is not set, all archs for visible cards are included for compilation.
If this is not desired, please set os.environ['TORCH_CUDA_ARCH_LIST'].
  warnings.warn(
Traceback (most recent call last):
  File "C:\Comfy\ComfyUI_windows_portable_2\ComfyUI\nodes.py", line 1931, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Comfy\ComfyUI_windows_portable_2\ComfyUI\custom_nodes\Comfyui-CatVTON\__init__.py", line 3, in <module>
    from .model.cloth_masker import AutoMasker as AM
  File "C:\Comfy\ComfyUI_windows_portable_2\ComfyUI\custom_nodes\Comfyui-CatVTON\model\cloth_masker.py", line 10, in <module>
    from ..model.DensePose import DensePose  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Comfy\ComfyUI_windows_portable_2\ComfyUI\custom_nodes\Comfyui-CatVTON\model\DensePose\__init__.py", line 12, in <module>
    from densepose import add_densepose_config
  File "C:\Comfy\ComfyUI_windows_portable_2\python_embeded\Lib\site-packages\densepose\__init__.py", line 2, in <module>    from .data.datasets import builtin  # just to register data
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Comfy\ComfyUI_windows_portable_2\python_embeded\Lib\site-packages\densepose\data\__init__.py", line 4, in <module>
    from .build import (
  File "C:\Comfy\ComfyUI_windows_portable_2\python_embeded\Lib\site-packages\densepose\data\build.py", line 13, in <module>
    from detectron2.data.build import build_detection_test_loader as d2_build_detection_test_loader
  File "C:\Comfy\ComfyUI_windows_portable_2\python_embeded\Lib\site-packages\detectron2\data\__init__.py", line 2, in <module>
    from . import transforms  # isort:skip
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Comfy\ComfyUI_windows_portable_2\python_embeded\Lib\site-packages\detectron2\data\transforms\__init__.py", line 4, in <module>
    from .transform import *
  File "C:\Comfy\ComfyUI_windows_portable_2\python_embeded\Lib\site-packages\detectron2\data\transforms\transform.py", line 36, in <module>
    class ExtentTransform(Transform):
  File "C:\Comfy\ComfyUI_windows_portable_2\python_embeded\Lib\site-packages\detectron2\data\transforms\transform.py", line 46, in ExtentTransform
    def __init__(self, src_rect, output_size, interp=Image.LINEAR, fill=0):
                                                     ^^^^^^^^^^^^
AttributeError: module 'PIL.Image' has no attribute 'LINEAR'

**Comment by toyxyz** [comment]
I downgraded the pillow version to 9.5.0 and it works. 

https://github.com/facebookresearch/detectron2/issues/5010#issuecomment-1752284625

**Comment by ycyy** [comment]
> I downgraded the pillow version to 9.5.0 and it works.我将枕头版本降级到 9.5.0，它可以工作。
> 
> [facebookresearch/detectron2#5010 (comment)](https://github.com/facebookresearch/detectron2/issues/5010#issuecomment-1752284625)
change “detectron2\data\transforms\transform.py, line 46” from LINEAR to BILINEAR

**Comment by landaship** [comment]
> First，type pip install to check if detectron2 and detectron2-densepose==0.6 has been installed successfully under your Comfyui python environment. as below pic shown ![image](https://github.com/user-attachments/assets/da81761b-75eb-43cf-aa69-c1678c008557) If not ,pls manually install detectron2 and densepose with below cli: pip install git+https://github.com/facebookresearch/detectron2.git@v0.6 pip install git+https://github.com/facebookresearch/detectron2.git@v0.6#subdirectory=projects/DensePose notice that before install detectron2 and densepose you need to install VS2019 and add VS2019 to your system environment variables path

请问用vs2022可以么？Is it OK to use vs2022?
