### ISSUE TITLE
automasker generator issue

### ISSUE THREAD

**Issue by BarryyyDrew** [pzc163/Comfyui-CatVTON#12]
got prompt
!!! Exception during processing!!! An error happened while trying to locate the files on the Hub and we cannot find the appropriate snapshot folder for the specified revision on the local disk. Please check your internet connection and try again.
Traceback (most recent call last):
  File "C:\Users\123\.conda\envs\comfy-catvton\lib\site-packages\urllib3\connection.py", line 196, in _new_conn
    sock = connection.create_connection(
  File "C:\Users\123\.conda\envs\comfy-catvton\lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    raise err
  File "C:\Users\123\.conda\envs\comfy-catvton\lib\site-packages\urllib3\util\connection.py", line 73, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

**Comment by BarryyyDrew** [comment]
i solve this issue, just add mirror to the path , like `os.environ["HF_ENDPOINT"] = "https://hf-mirror.com"` in the main.py
