### ISSUE TITLE
IMPORT FAILED

### ISSUE THREAD

**Issue by gghuanhuan** [pzc163/Comfyui-CatVTON#15]
Platform: Windows
Python version: 3.10.11
pytorch version: 2.3.1+cu121

`[2024-09-04 23:19] Traceback (most recent call last):
  File "D:\softwares\ComfyUI-aki-v1.3\nodes.py", line 1993, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\softwares\ComfyUI-aki-v1.3\custom_nodes\Comfyui-CatVTON\__init__.py", line 3, in <module>
    from .model.cloth_masker import AutoMasker as AM
  File "D:\softwares\ComfyUI-aki-v1.3\custom_nodes\Comfyui-CatVTON\model\cloth_masker.py", line 9, in <module>
    from ..model.SCHP import SCHP  # type: ignore
  File "D:\softwares\ComfyUI-aki-v1.3\custom_nodes\Comfyui-CatVTON\model\SCHP\__init__.py", line 1, in <module>
    from . import networks
  File "D:\softwares\ComfyUI-aki-v1.3\custom_nodes\Comfyui-CatVTON\model\SCHP\networks\__init__.py", line 3, in <module>
    from .AugmentCE2P import resnet101
  File "D:\softwares\ComfyUI-aki-v1.3\custom_nodes\Comfyui-CatVTON\model\SCHP\networks\AugmentCE2P.py", line 21, in <module>
    from ..modules import InPlaceABNSync
  File "D:\softwares\ComfyUI-aki-v1.3\custom_nodes\Comfyui-CatVTON\model\SCHP\modules\__init__.py", line 1, in <module>
    from .bn import ABN, InPlaceABN, InPlaceABNSync
  File "D:\softwares\ComfyUI-aki-v1.3\custom_nodes\Comfyui-CatVTON\model\SCHP\modules\bn.py", line 10, in <module>
    from .functions import *
  File "D:\softwares\ComfyUI-aki-v1.3\custom_nodes\Comfyui-CatVTON\model\SCHP\modules\functions.py", line 10, in <module>
    _backend = load(name="inplace_abn",
  File "D:\softwares\ComfyUI-aki-v1.3\python\lib\site-packages\torch\utils\cpp_extension.py", line 1309, in load
    return _jit_compile(
  File "D:\softwares\ComfyUI-aki-v1.3\python\lib\site-packages\torch\utils\cpp_extension.py", line 1719, in _jit_compile
    _write_ninja_file_and_build_library(
  File "D:\softwares\ComfyUI-aki-v1.3\python\lib\site-packages\torch\utils\cpp_extension.py", line 1809, in _write_ninja_file_and_build_library
    extra_ldflags = _prepare_ldflags(
  File "D:\softwares\ComfyUI-aki-v1.3\python\lib\site-packages\torch\utils\cpp_extension.py", line 1895, in _prepare_ldflags
    extra_ldflags.append(f'/LIBPATH:{_join_cuda_home("lib", "x64")}')
  File "D:\softwares\ComfyUI-aki-v1.3\python\lib\site-packages\torch\utils\cpp_extension.py", line 2419, in _join_cuda_home
    raise OSError('CUDA_HOME environment variable is not set. '
OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.

[2024-09-04 23:19] Cannot import D:\softwares\ComfyUI-aki-v1.3\custom_nodes\Comfyui-CatVTON module for custom nodes: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.`

**Comment by goodluck821** [comment]
I have the same erroe, how to solve it?????

**Comment by goodluck821** [comment]
AMD显卡用不了。
