### ISSUE TITLE
error: subprocess-exited-with-error

### ISSUE THREAD

**Issue by waaaok** [pzc163/Comfyui-CatVTON#3]
(.venv) D:\Comfyui-CatVTON>pip install git+https://github.com/facebookresearch/detectron2.git@v0.6
Collecting git+https://github.com/facebookresearch/detectron2.git@v0.6
  Cloning https://github.com/facebookresearch/detectron2.git (to revision v0.6) to c:\users\tt4090\appdata\local\temp\pip-req-build-y3_jrnnf
  Running command git clone --filter=blob:none --quiet https://github.com/facebookresearch/detectron2.git 'C:\Users\tt4090\AppData\Local\Temp\pip-req-build-y3_jrnnf'
  Running command git checkout -q d1e04565d3bec8719335b88be9e9b961bf3ec464
  Resolved https://github.com/facebookresearch/detectron2.git to commit d1e04565d3bec8719335b88be9e9b961bf3ec464
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "C:\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\tt4090\AppData\Local\Temp\pip-build-env-h0yeemmx\overlay\Lib\site-packages\setuptools\build_meta.py", line 327, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\tt4090\AppData\Local\Temp\pip-build-env-h0yeemmx\overlay\Lib\site-packages\setuptools\build_meta.py", line 297, in _get_build_requires
          self.run_setup()
        File "C:\Users\tt4090\AppData\Local\Temp\pip-build-env-h0yeemmx\overlay\Lib\site-packages\setuptools\build_meta.py", line 497, in run_setup
          super().run_setup(setup_script=setup_script)
        File "C:\Users\tt4090\AppData\Local\Temp\pip-build-env-h0yeemmx\overlay\Lib\site-packages\setuptools\build_meta.py", line 313, in run_setup
          exec(code, locals())
        File "<string>", line 10, in <module>
      ModuleNotFoundError: No module named 'torch'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

(.venv) D:\Comfyui-CatVTON>pip show torch
Name: torch
Version: 2.3.0+cu121
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: https://pytorch.org/
Author: PyTorch Team
Author-email: packages@pytorch.org
License: BSD-3
Location: C:\Python311\Lib\site-packages
Requires: filelock, fsspec, jinja2, mkl, networkx, sympy, typing-extensions
Required-by: torchaudio, torchvision
![微信截图_20240731033728](https://github.com/user-attachments/assets/df9da2ae-5844-4ad6-b457-14a235c3cb53)

**Comment by waaaok** [comment]
i have installed torch,but it said no module name torch.

**Comment by abcd1987zt** [comment]
我的也一样，太难弄了

**Comment by goodluck821** [comment]
（1）安装setuptools：
pip install --upgrade setuptools
（2）安装微软的VS Install，把你的操作系统包和改装的库装上：
pip install nes-py --no-cache-dir
pip install --upgrade pip setuptools wheel
（3）然后再次安装....模块试试：
pip install....。
